# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: access_control.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'access_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61\x63\x63\x65ss_control.proto\"\x19\n\nUIDRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\"2\n\x0e\x41\x63\x63\x65ssResponse\x12\x0f\n\x07granted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t29\n\rAccessControl\x12(\n\x08\x43heckUID\x12\x0b.UIDRequest\x1a\x0f.AccessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'access_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UIDREQUEST']._serialized_start=24
  _globals['_UIDREQUEST']._serialized_end=49
  _globals['_ACCESSRESPONSE']._serialized_start=51
  _globals['_ACCESSRESPONSE']._serialized_end=101
  _globals['_ACCESSCONTROL']._serialized_start=103
  _globals['_ACCESSCONTROL']._serialized_end=160
# @@protoc_insertion_point(module_scope)
